<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Name>Blue Mage Helper</Name>
        <Author>Infi, Sl0nderman, harbingerftw</Author>
        <Version>3.4.0.0</Version>
        <Punchline>Helps you fill out your Blue Mage Spellbook</Punchline>
        <Description>Adds a window to show all Blue Magic, letting you search for spells and then teleport or mark the location on your map or open the dutyfinder. Can also mark mobs in world that drop spells you need.</Description>
        <Tags>spells;spellbook;blu;blue</Tags>
        <CategoryTags>jobs</CategoryTags>
        <RepoUrl>https://github.com/harbingerftw/BlueMageHelper</RepoUrl>
        <ApplicableVersion>any</ApplicableVersion>
    </PropertyGroup>

    <PropertyGroup>
        <DalamudLibPath>$(appdata)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="images\icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="spells.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>
